config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
      member do
        get :following, :followers
      end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Beta
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
      <header class="navbar navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container-fluid">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            
            <%= link_to "Beauty Twin", root_path, id: "logo" %>
            
              <div class="nav-collapse">
              <ul class="nav pull-right">
                <li><%= link_to "Home", root_path %></li>
                <% if signed_in? %>
                  <li><%= link_to "Users", users_path %></li>
                  <li id="fat-menu" class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Profile", current_user %></li>
                      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                                    
                      <li class="divider"></li>
                      <li>
                        <%= link_to "Sign out", signout_path, method: "delete" %>
                      </li>
                    </ul>
                  </li>
                <% else %>
                  <li><%= link_to "Sign Up", signup_path %></li>
                  <li><%= link_to "Sign in", signin_path %></li>
                <% end %>
              </ul>

            </div>
            
          </div>
        </div>
        <div id="navbar-categories" class="navbar navbar-fixed">
          <div class="navbar-inner">
            <div class="container" style="width: auto;">
              <a class="brand" href="#"> Categories</a>
              <ul class="nav" role="navigation">

                <li class="dropdown">
                  <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">Makeup <b class="caret"></b></a>
                  <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="http://google.com">Cheeks</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#anotherAction"> Eyes</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Face</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Lips</a></li>
                  </ul>
                </li>
                <li class="dropdown">
                  <a href="#" id="drop2" role="button" class="dropdown-toggle" data-toggle="dropdown"> Skin Care <b class="caret"></b></a>
                  <ul class="dropdown-menu" role="menu" aria-labelledby="drop2">
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Anti-Aging</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Acne</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Daily Care</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Facial Hair Removal</a>
                    </li>
                  </ul>
                </li>
                <li class="dropdown">
                  <a href="#" id="drop2" role="button" class="dropdown-toggle" data-toggle="dropdown"> Hair <b class="caret"></b></a>
                  <ul class="dropdown-menu" role="menu" aria-labelledby="drop2">
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Damaged Hair</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Split Ends</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Frizz</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Oiliness</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Scalp Problems</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Coloring</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Haircuts</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Styles</a></li>

                  </ul>
                </li>
                <li class="dropdown">
                  <a href="#" id="drop2" role="button" class="dropdown-toggle" data-toggle="dropdown"> Body <b class="caret"></b></a>
                  <ul class="dropdown-menu" role="menu" aria-labelledby="drop2">
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Fragrance</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Nails</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Skin</a></li>
                  
                  </ul>
                </li>  
              </ul>
              <form class="navbar-search pull-right">
                <input type="text" class="search" placeholder="Search Questions">
              </form>
              
              <form class="navbar-search pull-right">
                <input type="text" class="search-ask" placeholder="Ask a question">
              
              </form>
            </div>
          </div>


        </div>
      </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
    
  </head>
  <body>
     <%= render 'layouts/header' %>
     <div class="container-fluid">
       <% flash.each do |key, value| %>
         <div class="alert alert-<%= key %>"><%= value %></div>
       <% end %>
       <%= yield %>
       <%= render 'layouts/footer' %>
       <%= debug(params) if Rails.env.development? %>
     </div>
  </body>
</html>